@file:Suppress("UnstableApiUsage")

/*
* This file was generated by the Gradle 'init' task.
*
* This is a general purpose Gradle build.
* To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
* This project uses @Incubating APIs which are subject to change.
*/


plugins {
    kotlin("jvm").version("2.4.10")
    id("maven-publish")
    id("com.github.ben-manes.versions").version("0.51.0")
    id("dev.architectury.loom").version("1.17.491")
    id("com.palantir.git-version").version("3.1.0")
}

repositories {
    mavenCentral()
    maven("https://jitpack.io")
    maven("https://maven.quiltmc.org/repository/release")
    maven("https://repo.nyon.dev/releases")
}

group = "tf.veriny.unova"
@Suppress("UNCHECKED_CAST")
val gitVersion = extra["gitVersion"] as groovy.lang.Closure<String>
version = gitVersion().drop(1)  // we tag with v0.7.x

//loom.runs.named("client") {
//    isIdeConfigGenerated = true
//   programArgs("--mimicPlayer", project.properties["fabricMimicPlayer"].toString())
//}

loom.forge {
    mixinConfig("lilligant.mixins.json")
    accessTransformer(rootProject.file("src/main/resources/META-INF/accesstransformer.cfg"))
    // convertAccessWideners = true
}

//loom.accessWidenerPath.set(rootProject.file("src/main/resources/lilligant.accesswidener"))

kotlin {
    explicitApi()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))

    "minecraft"("com.mojang:minecraft:1.20.1")

    // this odd mappings layout means we use QM names for everything, and yarn JD.
    mappings(loom.layered {
        mappings("net.fabricmc:yarn:1.20.1+build.10:v2")
        mappings("org.quiltmc:quilt-mappings:1.20.1+build.23:intermediary-v2")
    })

    "forge"("net.minecraftforge:forge:1.20.1-47.4.22")
    modImplementation("dev.nyon:KotlinLangForge:2.12.2-k2.4.10-2.0+forge")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }

    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.named<ProcessResources>("processResources") {
    inputs.property("version") { project.version }
    filesMatching("META-INF/mods.toml") { expand("version" to project.version) }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])

            pom {
                name.set(project.name)
                description.set("+1 atk +1 def +1 spe")
                licenses {
                    license {
                        name.set("MPL-2.0")
                        url.set("https://www.mozilla.org/en-US/MPL/2.0/")
                    }
                }

                developers {
                    developer {
                        id.set("Fuyukai")
                        name.set("Lura Skye")
                        url.set("https://veriny.tf")
                    }
                }
            }
        }
    }
}